import type { NotificationThread } from './types';

const LOREM_SHORT = 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam a lacus erat.';
const LOREM_LONG =
    'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam a lacus erat. Quisque mauris lectus,';

/**
 * Temporary mock threads replicating the Figma mockups until the backend
 * sends real data. "Own" reply messages are stamped with the authenticated
 * user's id/username so the `sender_user_id === auth.user.id` logic that
 * will drive live data can be exercised already.
 */
export function createMockThreads(
    currentUserId: number,
    currentUsername: string
): NotificationThread[] {
    return [
        {
            id: 1,
            type: 'instance_related',
            subject: 'Instance#2',
            title: null,
            is_accepted: null,
            is_rejected: null,
            quick_links: [
                { label: 'Instance #2', url: '#' },
                { label: 'Subproject New_Nov26', url: '#' },
            ],
            notifications: [
                {
                    id: 11,
                    notification_thread_id: 1,
                    sender_user_id: 101,
                    recipient_user_id: currentUserId,
                    body: LOREM_SHORT,
                    is_read: true,
                    sender_username: 'jackfrost',
                    sender_role: 'annotator',
                    date: 'March 28, 2026',
                },
                {
                    id: 12,
                    notification_thread_id: 1,
                    sender_user_id: currentUserId,
                    recipient_user_id: 101,
                    body: LOREM_LONG,
                    is_read: true,
                    sender_username: currentUsername,
                    sender_role: null,
                    date: 'March 29, 2026',
                },
                {
                    id: 13,
                    notification_thread_id: 1,
                    sender_user_id: 101,
                    recipient_user_id: currentUserId,
                    body: LOREM_SHORT,
                    is_read: false,
                    sender_username: 'jackfrost',
                    sender_role: 'annotator',
                    date: 'Today at 17:35',
                },
            ],
        },
        {
            id: 2,
            type: 'flag_notification',
            subject: 'Flagged Instance#4',
            title: null,
            is_accepted: null,
            is_rejected: null,
            quick_links: [
                { label: 'Flagged Instance #4', url: '#' },
                { label: 'Subproject New_Nov26', url: '#' },
            ],
            notifications: [
                {
                    id: 21,
                    notification_thread_id: 2,
                    sender_user_id: 102,
                    recipient_user_id: currentUserId,
                    body: LOREM_SHORT,
                    is_read: false,
                    sender_username: 'belleRivera',
                    sender_role: 'annotator',
                    date: '17:35',
                },
            ],
        },
        {
            id: 3,
            type: 'project_ownership',
            subject: 'Ownership',
            title: null,
            is_accepted: null,
            is_rejected: null,
            quick_links: [{ label: 'Project New_Nov26', url: '#' }],
            notifications: [
                {
                    id: 31,
                    notification_thread_id: 3,
                    sender_user_id: 103,
                    recipient_user_id: currentUserId,
                    body: 'wants to transfer the Ownership of Project New_Nov26 to you. This means that you will have access to… and to…\n\nDo you accept the Ownership?',
                    is_read: false,
                    sender_username: 'robertDowny',
                    sender_role: 'owner',
                    date: '17:35',
                },
            ],
        },
        {
            id: 4,
            type: 'project_invitation',
            subject: 'Invitation to Project',
            title: null,
            is_accepted: null,
            is_rejected: null,
            quick_links: [{ label: 'Project New_Nov26', url: '#' }],
            notifications: [
                {
                    id: 41,
                    notification_thread_id: 4,
                    sender_user_id: 103,
                    recipient_user_id: currentUserId,
                    body: 'invites you to join Project New_Nov26 as a Manager.\n\nDo you accept the invitation?',
                    is_read: false,
                    sender_username: 'robertDowny',
                    sender_role: 'manager',
                    date: '17:35',
                },
            ],
        },
        {
            id: 5,
            type: 'announcement',
            subject: 'Subproject Gamma_Nov11',
            title: null,
            is_accepted: null,
            is_rejected: null,
            quick_links: [{ label: 'Subproject Gamma_Nov11', url: '#' }],
            notifications: [
                {
                    id: 51,
                    notification_thread_id: 5,
                    sender_user_id: 104,
                    recipient_user_id: currentUserId,
                    body: LOREM_SHORT,
                    is_read: true,
                    sender_username: 'kevinNash',
                    sender_role: 'owner',
                    date: '19:01',
                },
            ],
        },
        {
            id: 6,
            type: 'info',
            subject: null,
            title: 'Profile edit',
            is_accepted: null,
            is_rejected: null,
            quick_links: [],
            notifications: [
                {
                    id: 61,
                    notification_thread_id: 6,
                    sender_user_id: null,
                    recipient_user_id: currentUserId,
                    body: '@ggianna just edited your profile',
                    is_read: false,
                    sender_username: null,
                    sender_role: null,
                    date: '12/03/26',
                },
            ],
        },
        {
            id: 7,
            type: 'info',
            subject: null,
            title: 'New Project',
            is_accepted: null,
            is_rejected: null,
            quick_links: [],
            notifications: [
                {
                    id: 71,
                    notification_thread_id: 7,
                    sender_user_id: null,
                    recipient_user_id: currentUserId,
                    body: '@ggianna just added you to his project',
                    is_read: true,
                    sender_username: null,
                    sender_role: null,
                    date: '11/03/26',
                },
            ],
        },
        {
            id: 8,
            type: 'warning',
            subject: null,
            title: 'Overdue Date Approaching',
            is_accepted: null,
            is_rejected: null,
            quick_links: [],
            notifications: [
                {
                    id: 81,
                    notification_thread_id: 8,
                    sender_user_id: null,
                    recipient_user_id: currentUserId,
                    body: 'Subproject New Nov26 will surpass due date in 3 days',
                    is_read: true,
                    sender_username: null,
                    sender_role: null,
                    date: '11/03/26',
                },
            ],
        },
        {
            id: 9,
            type: 'warning',
            subject: null,
            title: 'Subproject Overdue',
            is_accepted: null,
            is_rejected: null,
            quick_links: [],
            notifications: [
                {
                    id: 91,
                    notification_thread_id: 9,
                    sender_user_id: null,
                    recipient_user_id: currentUserId,
                    body: 'Subproject New Nov26 surpassed due date today',
                    is_read: true,
                    sender_username: null,
                    sender_role: null,
                    date: '11/03/26',
                },
            ],
        },
        {
            id: 10,
            type: 'project_ownership',
            subject: 'Ownership',
            title: null,
            is_accepted: true,
            is_rejected: null,
            quick_links: [{ label: 'Project Beta_Oct14', url: '#' }],
            notifications: [
                {
                    id: 101,
                    notification_thread_id: 10,
                    sender_user_id: 105,
                    recipient_user_id: currentUserId,
                    body: LOREM_SHORT,
                    is_read: true,
                    sender_username: 'annaKendrick',
                    sender_role: 'manager',
                    date: '10/03/26',
                },
            ],
        },
    ];
}
